wandb_project: '3_FEA'
wandb_team: 'terumo-binary'
n_folds: 5
seed: 42
num_workers: 4
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 300
freeze: False
wandb_on: True
wandb_key: '273b6e50d83b95fd3a12d6544e5d48bf5afa49e2'
wandb_save_checkpoint: True
patience: 100
model_name: '3_FEA'
data_dir: './data/bracs/binary/binary_3_FEA'
classes: ['_others', '3_FEA']
